NodeVersion="18.19.1"
nodeBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
Frameworks="Next.js"
compressedNodeModulesFile="node_modules.tar.gz"
OutputDirPath=".next"
OperationId="03d70dcea9a2b3bf"
SourceDirectoryInBuildContainer="/tmp/8dc8ed44604d4b4"
PlatformName="nodejs"
CompressDestinationDir="false"
